=== sillypantscoder/wiki/ns_schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://jason.harromans.com/coltsuperexpress/game.schema.json",
	"title": "Namespace",
	"description": "Definition of a namespace",
	"type": "object",
	"properties": {
		"fields": {
			"description": "The list of fields pages in this namespace should include",
			"type": "object"
		},
		"defaultPage": {
			"description": "The name of the default page in this namespace",
			"anyOf": [
				{"type": "null"},
				{"type": "string"}
			]
		},
		"content": {
			"description": "(Handlebars-encoded string)",
			"type": "string"
		},
		"files": {
			"description": "List of additional files to host",
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"properties": {
					"type": {
						"description": "The MIME type to serve the file with (Handlebars-encoded string)",
						"type": "string"
					},
					"content": {
						"description": "The content to send (Handlebars-encoded string)",
						"type": "string"
					}
				},
				"additionalProperties": false
			}
		}
	},
	"additionalProperties": false,
	"$defs": {}
}

=== sillypantscoder/wiki/pages/Image/ns.json
{
	"fields": {
		"type": "text",
		"data": "file"
	},
	"defaultPage": null,
	"content": "$END<h5 style=\"margin: 0; padding: 0; color: gray; font-weight: normal;\">{{pagens}}:{{pagename}}</h5>\n<h1 style=\"margin-top: 0;\">{{pagename}}</h1>\n<img src=\"data:image/{{field type png}};base64,{{field64 data }}\">",
	"files": {
		"image": {"type": "image/{{field type png}}", "content": "{{field data }}"}
	}
}
